#!/bin/bash
sudo chown -R $USER /var/www/html/calculator
cd ~
curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
sudo bash /tmp/nodesource_setup.sh
sudo apt install nodejs
cd /var/www/html/calculator
npm install
npm start 
